name: Generate Artifacts

on:
  workflow_dispatch:
    inputs:
      yaak_version:
        type: string
        description: Version used to build Fiak
      fiak_version:
        type: string
        description: Version of Fiak

jobs:
  build-artifacts:
    permissions:
      contents: write

    name: Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            yaak_arch: 'arm64'
            os: 'macos'
            targets: 'aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            yaak_arch: 'x64'
            os: 'macos'
            targets: 'x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
            yaak_arch: 'x64'
            os: 'ubuntu'
            targets: ''
          - platform: 'ubuntu-22.04-arm'
            args: ''
            yaak_arch: 'arm64'
            os: 'ubuntu'
            targets: ''
          - platform: 'windows-latest'
            args: ''
            yaak_arch: 'x64'
            os: 'windows'
            targets: ''
          - platform: 'windows-latest'
            args: '--target aarch64-pc-windows-msvc'
            yaak_arch: 'arm64'
            os: 'windows'
            targets: 'aarch64-pc-windows-msvc'
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: actions/setup-node@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets }}

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: 'yaak/src-tauri'
          shared-key: ci
          cache-on-failure: true

      - name: install dependencies
        if: matrix.os == 'macos'
        run: |
          brew install quilt

      - name: install dependencies
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils quilt

      - name: install dependencies
        if: matrix.os == 'windows'
        run: |
          C:\msys64\usr\bin\bash -lc "pacman -S --noconfirm quilt"
        shell: pwsh

      - if: matrix.os != 'windows'
        run: quilt push -a

      - if: matrix.os == 'windows'
        run: |
          C:\msys64\usr\bin\bash.exe -lc 'cd "$(cygpath -u "$GITHUB_WORKSPACE")" && quilt push -a'
        shell: pwsh

      - name: protoc for plugin-runtime
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm ci
        working-directory: ./yaak

      - run: npm run replace-version
        working-directory: ./yaak
        env:
          YAAK_VERSION: v${{ inputs.fiak_version }}

      - uses: tauri-apps/tauri-action@v0
        env:
          YAAK_TARGET_ARCH: ${{ matrix.yaak_arch }}

          ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

          # Apple
          APPLE_CERTIFICATE: ${{ matrix.os == 'macos' && secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ matrix.os == 'macos' && secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ matrix.os == 'macos' && secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ matrix.os == 'macos' && secrets.APPLE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ matrix.os == 'macos' && secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_TEAM_ID: ${{ matrix.os == 'macos' && secrets.APPLE_TEAM_ID }}
        with:
          projectPath: ./yaak
          tagName: 'v__VERSION__'
          releaseName: 'Release __VERSION__'
          releaseBody: '> Based on [Yaak v${{ inputs.yaak_version }}](https://github.com/mountain-loop/yaak/tree/v${{ inputs.yaak_version }}). For details on upstream changes, see <https://yaak.app/blog/${{ inputs.yaak_version }}>. The changelog for this Fiak release is provided below.\n\n(TBD)'
          includeUpdaterJson: true
          releaseDraft: true
          prerelease: false
          args: '${{ matrix.args }} --config src-tauri/tauri.release.conf.json'
